FROM php:7.1.3-fpm-alpine

MAINTAINER Mihail Krastev <mlinuxgada@gmail.com>


RUN apk update \
	&& apk upgrade \
	&& apk add libxml2-dev \ 
	&& docker-php-ext-install bcmath exif mysqli opcache pdo pdo_mysql soap \
	#&& pecl install redis-3.1.0 \
    #&& pecl install xdebug-2.5.0 \
    && docker-php-ext-enable bcmath exif mysqli opcache pdo pdo_mysql soap \
	&& rm /var/cache/apk/*

# Copy xdebug configration for remote debugging
COPY ./xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini


# Copy opcache configration
COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.ini

ADD ./php.ini /usr/local/etc/php/conf.d
ADD ./fpm.pool.conf /usr/local/etc/php-fpm.d/

WORKDIR /var/www

CMD ["php-fpm"]

EXPOSE 9000
